require('dotenv').config()
const express = require('express')
const cors = require('cors')
const http = require('http')
const { Server } = require('socket.io')
const cron = require('node-cron')
const { router: authRouter } = require('./auth')
const cache = require('./cache')
const routes = require('./routes')
const app = express()
app.use(cors())
app.use(express.json())
app.use(authRouter)
app.use(routes)
const server = http.createServer(app)
const io = new Server(server, { cors: { origin: '*' } })
io.on('connection', () => {})
cron.schedule('0 * * * *', () =>
    cache.rebuild().then(() => io.emit('cacheUpdated'))
)
server.listen(4000)
cache.rebuild().then(() => io.emit('cacheUpdated'))
